url: https://niccokunzmann.github.io
permalink: /blog/:year-:month-:day/:title
sourcecode:
  repository: "https://github.com/niccokunzmann/niccokunzmann.github.io"
  root: "https://github.com/niccokunzmann/niccokunzmann.github.io/tree/master"
